=== simranshaikh/TR-doc/anchalj2ee/TESTXML/bank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/bank"
 xmlns:tns="http://www.example.org/bank" 
 elementFormDefault="qualified">
 <!-- name element -->
 	 	<xsd:element name="name">
         <xsd:complexType>
 	      <xsd:sequence>
 		     <xsd:element name="fname" type="xsd:string"/>
 		     <xsd:element name="lname" type="xsd:string"/>
 	      </xsd:sequence>
         </xsd:complexType>
        </xsd:element>
 <!-- balance element -->
  	   <xsd:element name="balance">
    	<xsd:complexType>
    	 <xsd:simpleContent>
 		<xsd:extension base="xsd:double">
  		<xsd:attribute name="currency" type="xsd:string" fixed="Rs."/>
    </xsd:extension>
   </xsd:simpleContent>
  </xsd:complexType>
 </xsd:element>
 <!-- card element -->
 <xsd:element name="card">
  <xsd:complexType>
   <xsd:attribute name="no" type="xsd:NMTOKENS" use="required"/>
  </xsd:complexType>
 </xsd:element>
 <!--cheques element  -->
  <xsd:element name="cheques">
  <xsd:complexType>
   <xsd:attribute name="nos" type="xsd:NMTOKEN" use="required"/>
  </xsd:complexType>
 </xsd:element>
 <!-- mobile element -->
  <xsd:element name="mobile">
    <xsd:simpleType>
     <xsd:restriction base="xsd:string">
       <xsd:pattern value="[0-9]{10,10}"/>
     </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <!-- account element -->
  	<xsd:element name="account">
  	<xsd:complexType>
  	<xsd:sequence>
  	<xsd:element name="accno" type="xsd:int"/>
  <xsd:element ref="tns:name"/>
  <xsd:element ref="tns:balance"/>
  <xsd:element ref="tns:card"/>
  <xsd:element ref="tns:cheques"/>
  <xsd:element ref="tns:mobile"/>
  <xsd:element name="email" type="xsd:string"/>
  </xsd:sequence>
  <xsd:attribute name="type" default="SAV">
  <xsd:simpleType>  
  <xsd:restriction base="xsd:string">
  <xsd:enumeration value="SAV"/>
  <xsd:enumeration value="CURR"/>
  </xsd:restriction>
  </xsd:simpleType>
  </xsd:attribute>
  </xsd:complexType>
  </xsd:element>
  <!-- branch element -->
  <xsd:element name="branch">
  <xsd:complexType>
  <xsd:simpleContent>
  <xsd:extension base="xsd:string">
  <xsd:attribute name="code">
  <xsd:simpleType>
  <xsd:restriction base="xsd:string">
  <xsd:minLength value="3"/>
  <xsd:maxLength value="6"/>
  </xsd:restriction>
  </xsd:simpleType>
  </xsd:attribute>
  </xsd:extension>
  </xsd:simpleContent>
  </xsd:complexType>
  </xsd:element>
  <!-- bank_name element -->
  <xsd:element name="bank_name">
  <xsd:simpleType>
  <xsd:restriction base="xsd:string">
  	<xsd:maxLength value="30"/>
  	<xsd:minLength value="5"/>
  	</xsd:restriction>
  	</xsd:simpleType>
  	</xsd:element>
  	<!-- bank element -->
  	<xsd:element name="bank">
  	<xsd:complexType>
  	<xsd:sequence>
  	<xsd:element ref="tns:bank_name"/>
  	<xsd:element ref="tns:account" minOccurs="1" maxOccurs="5"/>
  	</xsd:sequence>
  	</xsd:complexType>
  	</xsd:element>
 </xsd:schema>

=== simranshaikh/TR-doc/anchalj2ee/TESTXML/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:account type="SAV" xmlns:tns="http://www.example.org/bank" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/bank bank.xsd ">
  <tns:accno>0</tns:accno>
  <tns:name>
    <tns:fname>tns:fname</tns:fname>
    <tns:lname>tns:lname</tns:lname>
  </tns:name>
  <tns:balance currency="Rs.">0.0</tns:balance>
  <tns:card no="NMTOKENS"/>
  <tns:cheques nos="NMTOKEN"/>
  <tns:mobile>1234567891</tns:mobile>
  <tns:email>tns:email</tns:email>
</tns:account>
